# Generated by Django 4.2 on 2023-05-01 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mytables', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rest',
            name='city',
            field=models.CharField(blank='False'),
        ),
        migrations.AddField(
            model_name='rest',
            name='restName',
            field=models.CharField(blank='False'),
        ),
    ]
