# Generated by Django 4.2 on 2023-05-01 11:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mytables', '0002_rest_city_rest_restname'),
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('userId', models.IntegerField(primary_key='True', serialize=False)),
                ('userName', models.CharField(blank='False')),
                ('email', models.CharField(blank='False')),
            ],
        ),
        migrations.CreateModel(
            name='item',
            fields=[
                ('itemId', models.IntegerField(primary_key='True', serialize=False)),
                ('itemName', models.CharField(blank='False')),
                ('itemPrice', models.FloatField(blank='False')),
                ('restId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mytables.rest')),
            ],
        ),
        migrations.CreateModel(
            name='discount',
            fields=[
                ('disId', models.IntegerField(primary_key='True', serialize=False)),
                ('disPrice', models.FloatField(blank='False')),
                ('itemId', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mytables.item')),
            ],
        ),
    ]
