# Generated by Django 4.2 on 2023-05-01 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mytables', '0004_alter_rest_city_alter_rest_restname_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='disId',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='item',
            name='itemId',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='item',
            name='itemName',
            field=models.CharField(blank='False', max_length=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='orderId',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='rest',
            name='city',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='rest',
            name='restId',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='rest',
            name='restName',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.CharField(blank='False', max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='userId',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='userName',
            field=models.CharField(blank='False', max_length=100),
        ),
    ]
