# Generated by Django 4.2 on 2023-04-30 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flightsApp', '0007_alter_flight_flight_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flight',
            name='flight_name',
        ),
    ]
