# Generated by Django 4.2 on 2023-04-29 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_org', '0003_alter_booking_options_alter_customer_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='date_of_booking',
            field=models.DateField(default='23-04-2023', null=True),
        ),
    ]
