# Generated by Django 4.2 on 2023-04-29 11:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event_org', '0004_alter_booking_date_of_booking'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'ordering': ['booking_id']},
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='Booking_id',
            new_name='booking_id',
        ),
        migrations.AlterField(
            model_name='booking',
            name='customer_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='event_org.customer'),
        ),
    ]
