# Generated by Django 3.2.12 on 2023-04-29 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event_org', '0006_alter_customer_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='customer_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='event_org.customer'),
        ),
    ]
