# Generated by Django 3.2.12 on 2023-04-29 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_org', '0007_event_customer_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(default='987654321', max_length=20),
        ),
    ]
