# Generated by Django 4.2 on 2023-05-01 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='rest',
            fields=[
                ('restId', models.IntegerField(primary_key='True', serialize=False)),
            ],
        ),
    ]
