# Generated by Django 4.2 on 2023-05-01 11:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mytables', '0003_user_item_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rest',
            name='city',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='rest',
            name='restName',
            field=models.CharField(),
        ),
        migrations.CreateModel(
            name='order',
            fields=[
                ('orderId', models.IntegerField(primary_key='True', serialize=False)),
                ('itemId', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mytables.item')),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mytables.user')),
            ],
        ),
    ]
