# Generated by Django 4.2 on 2023-04-30 06:41

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='actor',
            fields=[
                ('actor_id', models.AutoField(primary_key=True, serialize=False)),
                ('actor_name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='director',
            fields=[
                ('director_id', models.AutoField(primary_key=True, serialize=False)),
                ('director_name', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='genre',
            fields=[
                ('genre_id', models.AutoField(primary_key=True, serialize=False)),
                ('genre_type', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='movie',
            fields=[
                ('movie_id', models.AutoField(primary_key=True, serialize=False)),
                ('movie_name', models.CharField(max_length=100)),
                ('release_year', models.DateField(auto_now_add=True, null=True)),
                ('rating', models.DecimalField(decimal_places=2, max_digits=3)),
            ],
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=100)),
                ('user_email', models.EmailField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='watchlist',
            fields=[
                ('watchlist_id', models.AutoField(primary_key=True, serialize=False)),
                ('movie_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mmsapp.movie')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mmsapp.user')),
            ],
        ),
        migrations.CreateModel(
            name='review',
            fields=[
                ('review_id', models.AutoField(primary_key=True, serialize=False)),
                ('rating', models.IntegerField()),
                ('comment', models.CharField(max_length=100)),
                ('date', models.DateField(default=datetime.datetime.now)),
                ('movie_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mmsapp.movie')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mmsapp.user')),
            ],
        ),
        migrations.CreateModel(
            name='movie_genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mmsapp.genre')),
                ('movie_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mmsapp.movie')),
            ],
        ),
        migrations.CreateModel(
            name='movie_director',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('director_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mmsapp.director')),
                ('movie_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mmsapp.movie')),
            ],
        ),
        migrations.CreateModel(
            name='movie_cast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=100)),
                ('actor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mmsapp.actor')),
                ('movie_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mmsapp.movie')),
            ],
        ),
    ]
