# Generated by Django 4.2 on 2023-04-30 12:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mmsapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='genre_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='mmsapp.genre'),
        ),
        migrations.AlterField(
            model_name='movie_cast',
            name='actor_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mmsapp.user'),
        ),
        migrations.AlterField(
            model_name='movie_director',
            name='director_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mmsapp.user'),
        ),
        migrations.DeleteModel(
            name='actor',
        ),
        migrations.DeleteModel(
            name='director',
        ),
    ]
