# Generated by Django 4.2 on 2023-04-30 12:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mmsapp', '0003_alter_movie_genre_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='genre_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mmsapp.genre'),
        ),
    ]
