# Generated by Django 4.2 on 2023-05-25 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mmsapp', '0005_moviedirector_rename_movie_cast_moviecast_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Moviegenre',
        ),
    ]
