# Generated by Django 4.2 on 2023-04-27 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='supplier',
            fields=[
                ('supplier_id', models.IntegerField(primary_key='True', serialize=False)),
                ('supplier_name', models.CharField(max_length=100)),
                ('contact_person', models.CharField(max_length=100)),
            ],
        ),
    ]
