# Generated by Django 4.2 on 2023-04-27 10:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('VendMan', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='customer',
            fields=[
                ('customer_id', models.IntegerField(primary_key='True', serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='product',
            fields=[
                ('product_id', models.IntegerField(primary_key='True', serialize=False)),
                ('product_name', models.CharField(max_length=200)),
                ('supplier_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='VendMan.supplier')),
            ],
        ),
        migrations.CreateModel(
            name='order',
            fields=[
                ('order_id', models.IntegerField(primary_key='True', serialize=False)),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='VendMan.customer')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='VendMan.product')),
            ],
        ),
    ]
