# Generated by Django 4.2 on 2023-04-30 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flightsApp', '0002_rename_uset_id_user_user_id_remove_user_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='myUser',
        ),
    ]
