# Generated by Django 4.2 on 2023-04-30 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flightsApp', '0003_rename_user_myuser'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='myUser',
            new_name='User',
        ),
    ]
