# Generated by Django 4.2 on 2023-04-30 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flightsApp', '0005_rename_uset_id_user_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='flight_name',
            field=models.CharField(default='indigo', max_length=50),
        ),
    ]
