# Generated by Django 4.2 on 2023-04-30 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flightsApp', '0006_flight_flight_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='flight_name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
